# Generated by Django 5.0.3 on 2024-03-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo_app',
            new_name='Task',
        ),
    ]
